//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Path
    {
        public int id { get; set; }
        public string id_group { get; set; }
        public string paths { get; set; }
        public string link { get; set; }
    }
}
