//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parse_VK.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\DataBase.mdf;" +
            "Integrated Security=True")]
        public string MyDataBaseConnectionString {
            get {
                return ((string)(this["MyDataBaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\DataBase.mdf;" +
            "Integrated Security=True;Connect Timeout=30")]
        public string DataBaseConnectionString {
            get {
                return ((string)(this["DataBaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\bin\\x64\\Debug" +
            "\\Database1.mdf;Integrated Security=True;Connect Timeout=30")]
        public string Database1ConnectionString {
            get {
                return ((string)(this["Database1ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=C:\\Users\\Flax\\Desktop\\Parse_V" +
            "K(v.1.3)\\DataBaseService\\Database1.mdf;Integrated Security=True")]
        public string Database1ConnectionString1 {
            get {
                return ((string)(this["Database1ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\Database1.mdf" +
            ";Integrated Security=True")]
        public string Database1ConnectionString2 {
            get {
                return ((string)(this["Database1ConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\Dick.mdf;Inte" +
            "grated Security=True")]
        public string DickConnectionString {
            get {
                return ((string)(this["DickConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\Database1.mdf" +
            ";Integrated Security=True;Connect Timeout=30")]
        public string Database1ConnectionString3 {
            get {
                return ((string)(this["Database1ConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=C:\\USERS\\FLAX\\DESKTOP\\PARSE_VK" +
            "(V.1.3)\\PARSE_VK\\BIN\\X64\\DEBUG\\DATABASE1.MDF;Integrated Security=True;Connect Ti" +
            "meout=30;Encrypt=False;TrustServerCertificate=False")]
        public string C__USERS_FLAX_DESKTOP_PARSE_VK_V_1_3__PARSE_VK_BIN_X64_DEBUG_DATABASE1_MDFConnectionString {
            get {
                return ((string)(this["C__USERS_FLAX_DESKTOP_PARSE_VK_V_1_3__PARSE_VK_BIN_X64_DEBUG_DATABASE1_MDFConnect" +
                    "ionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=C:\\USERS\\FLAX\\DESKTOP\\PARSE_VK" +
            "(V.1.3)\\PARSE_VK\\LASTDATABASE.MDF;Integrated Security=True;Connect Timeout=30;En" +
            "crypt=False;TrustServerCertificate=False")]
        public string C__USERS_FLAX_DESKTOP_PARSE_VK_V_1_3__PARSE_VK_LASTDATABASE_MDFConnectionString {
            get {
                return ((string)(this["C__USERS_FLAX_DESKTOP_PARSE_VK_V_1_3__PARSE_VK_LASTDATABASE_MDFConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\LastDataBase." +
            "mdf;Integrated Security=True;Connect Timeout=30")]
        public string LastDataBaseConnectionString {
            get {
                return ((string)(this["LastDataBaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\Work.mdf;Inte" +
            "grated Security=True")]
        public string WorkConnectionString {
            get {
                return ((string)(this["WorkConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=C:\\USERS\\FLAX\\DESKTOP\\PARSE_VK" +
            "(V.1.3)\\PARSE_VK\\BIN\\X64\\DEBUG\\WORK.MDF;Integrated Security=True;Connect Timeout" +
            "=30;Encrypt=False;TrustServerCertificate=False")]
        public string C__USERS_FLAX_DESKTOP_PARSE_VK_V_1_3__PARSE_VK_BIN_X64_DEBUG_WORK_MDFConnectionString {
            get {
                return ((string)(this["C__USERS_FLAX_DESKTOP_PARSE_VK_V_1_3__PARSE_VK_BIN_X64_DEBUG_WORK_MDFConnectionSt" +
                    "ring"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=\"C:\\Users\\Flax\\Desktop\\Операц" +
            "ионные системы\\My projects\\Parse_VK(v1.6)\\DataBaseService\\Inf.mdf\";Integrated Se" +
            "curity=True")]
        public string InfConnectionString {
            get {
                return ((string)(this["InfConnectionString"]));
            }
        }
    }
}
